# Generated by Django 4.2.29 on 2026-04-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_report_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
